### ISSUE TITLE
How to fix This Warning?

### ISSUE THREAD

**Issue by StellarKuldeep** [orucanil/StringFormatter#5]
I got this warning  at below code.. how can I fix this?

**'init' is deprecated: CountableRange is now Range. No need to convert any more.**

```
subscript (i: Int) -> String {
    return self[Range(i ..< i + 1)]
}
```

**Comment by schenkty** [comment]
Hey @StellarKuldeep, you can fix the warning by replacing the following

Old Code: `return self[Range(i ..< i + 1)]`
New Code: `return self[i ..< i + 1]`

**Comment by orucanil** [comment]
Fixed
